### ISSUE TITLE
Convert Wiki Pages to Github Pages Documentation

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#152]
Several pages have been written and revised adequately within the project wiki and should be migrated to the Github Pages site for a more permanent location. Most of these came out of the overall documentation initiative described in #94.
- [ ] Project setup with web-starter and yeoman (#87)
  - [Creating a project](https://github.com/forumone/web-starter/wiki/Creating-a-project)
- [ ] Project maintenance and updating web-starter (#91)
  - [Updating a project](https://github.com/forumone/web-starter/wiki/Creating-a-project#using-the-project-generator)
- [ ] Developer documentation and resources (#93)
  - [Developer Documentation and Resources](https://github.com/forumone/web-starter/wiki/Developer-Documentation-and-Resources)
- [ ] Creating and Modifying Grunt Tasks (#95)
  - [Build Process](https://github.com/forumone/web-starter/wiki/Build-process)
