### ISSUE TITLE
Roadmap: Project Documentation

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#94]
Project documentation for usage and best practices is lacking currently. Let's explore some of the primary areas that are needed and project a series of tasks to complete.
## Needed Documentation
- [x] Project setup with web-starter and yeoman (#87)
- [x] Project maintenance and updating web-starter (#91)
- [x] Project support and contribution (#88)
- [ ] Developer documentation and resources (#93)
- [x] Documentation: Creating and Modifying Grunt Tasks (#95)
